Initial DayZ Documentation
muttleyxd/arma3-unix-launcher pull request #198
Opened 2022-02-09 01:10 UTC by Eutyches

You might also wish to change the name of the repository to "arma3-dayz-unix-launcher."

2022-02-10 10:04 UTC, muttleyxd requested changes

2022-02-10 10:04 UTC, muttleyxd commented on README.md
> +For Debian based distributions (Debian, Ubuntu), Arch based distributions (Arch, Manjaro), and MacOS there are packages available in [releases tab!](https://github.com/muttleyxd/arma3-unix-launcher/r
If we're finally updating this I would mention AppImage as it works anywhere where we have GNU/Linux.

```
There are GNU/Linux and macOS packages available in [releases tab!](https://github.com/muttleyxd/arma3-unix-launcher/releases).
For GNU/Linux following package types are available:
- pkg.tar.xz package (for Arch Linux, Manjaro and few others) (arma3-unix-launcher)
- deb package for Ubuntu 16.04 and 18.04 (arma3-unix-launcher)
- dmg package for macOS (arma3-unix-launcher)
- AppImage packages for any GNU/Linux running glibc 2.23 or newer (arma3-unix-launcher and dayz-linux-launcher)
```

2022-02-11 22:34 UTC, graves501 commented on README.md
> +For Arch based distributions there's an AUR package available (for Arma 3). It iss called `arma3-unix-launcher-bin`.
`It iss called` -> `It is called`

2022-03-03 13:31 UTC, muttleyxd commented
@Eutyches I plan to merge it soon. Will you have some time to take a look at changes we have proposed?

2022-03-06 22:16 UTC, Eutyches commented
> @Eutyches I plan to merge it soon. Will you have some time to take a look at changes we have proposed?

Updated with your suggested changes and a final editorial pass. Pardon the delay. Thank you again :smile:

2022-03-07 09:43 UTC, merged